/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2b36b7d1-705c-47b6-bd47-85bee39a53ed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OtDOuHBqD",
    "aws_user_pools_web_client_id": "gq85n566n3k9qf6sdfsq84rb0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dbfovdew6ndh7nrkzxojvxjtgy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-m7xcbje7hzb5tjqspjjyjfx2bq",
    "aws_user_files_s3_bucket": "coursestorage02232-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
